[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python3 app.py"
healthcheckPath = "/api"
restartPolicyType = "ON_FAILURE"

[[services]]
name = "cinephile"
internalPort = 8000
